---
- hosts: all

  tasks:

    - name: Disable the ufw firewall (on Ubuntu, if configured).
      service:
        name: ufw
        state: stopped
        enabled: false
      when:
        - ansible_distribution == "Ubuntu"
        #- firewall_disable_ufw
        #- ufw_installed.rc == 0


