# sudo ansible servers -m ping -i inventory.ini -u root
# sudo ansible-playbook -i inventory.ini ServerPrepare.yml -u root

---
- hosts: all

  become: yes
  vars:
    user: "{{ ansible_env.USER }}"

  tasks:


    - name: Print initialization (0)
      debug:
        msg: "Installing docker 24.0.0 on ubuntu 22.04 is going to start ..."


    - name: Disable swap (1)
      shell: |
        swapoff -a


    - name: Disable swap in fstab (2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'


    - name: Configure hostname (3)
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      become: true


    - name: Add IP address of all hosts to all hosts (4)
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"


    - name: Disable the ufw firewall (on Ubuntu, if configured). (5)
      service:
        name: ufw
        state: stopped
        enabled: false
      when:
        - ansible_distribution == "Ubuntu"


    - name: Install required packages (6)
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common


    - name: Create directory for Docker's GPG key (6.1)
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'


    - name: Add Docker GPG key (6.2)
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc


    - name: Get DEB architecture 
      shell: dpkg --print-architecture
      register: deb_architecture


    - name: Print DEB architecture
      debug:
        msg: "deb_architecture.stdout: {{ deb_architecture.stdout }}"


    - name: Add Docker repo  (6.3)     
      ansible.builtin.apt_repository:
        filename: docker
        repo: 'deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] 
                https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
        state: present


    - name: Update Repository cache (7)
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

    - name: Downloding docker (8)
      debug:
        msg: "Downloding docker & containerd ..."


    - name: Install Docker stuff (9)
      apt:
        pkg:
          - docker-ce=5:24.0.0-1~ubuntu.22.04~jammy
          - docker-ce-cli=5:24.0.0-1~ubuntu.22.04~jammy
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    

    - name: Enable and start Docker services (10)
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service

        
